### ISSUE TITLE
Original images were deleted!!!

### ISSUE THREAD

**Issue by sweihub** [leblancfg/autocrop#105]
Hi, there

I think it's scary that the original images were removed after running the command, why don't you leave the original images?

Two issues

1.  Original images were removed without explanations, please DON'T! Thanks
2. Cannot recurse into the image folder

**Comment by joerg-s** [comment]
Hi,
I just tried autocrop and like the results very much.
However, I was pretty glad that I had a backup of the original files, because autocrop in fact deletes them in the input-folder even if an output folder is given and used. I consider that a grave and dangerous mistake which should be corrected asap, in order to make this the very good tool it could actually be.

Thanks and kind regards,
Jörg

**Comment by HWiese1980** [comment]
Holy crap @leblancfg are you insane??? I've just lost a pretty large number of really precious pictures because your program deleted the original files without any warning!!! What the hell made you think that was a good idea??? 🤬🤬🤬 Who will compensate me for that loss? You? I'm sure you won't! 

I can't express how furious I am!!! You fucked up big time!

**Comment by joerg-s** [comment]
If someone cares: There are two lines in the file cli.py:

shutil.**move**(input_filename, output_filename)
shutil.**move**(input_filename, reject_filename)

Changing them to shutil.**copy**(...) seems to be the solution.

Just my two cents, I am not the author of autocrop!
So be careful and have your backups...
Jörg

**Comment by HWiese1980** [comment]
Yeah! Great! How can we warn others of this massive, critical fuck-up? Excuse my wording, I'm still furious as hell!

**Comment by joerg-s** [comment]
That's the problem: We all came here **after** using it and then finding the input directory wiped out. I just sent an email to François Leblanc asking for his attention, maybe he wakes up. I don't know any other way to warn others.

(I fully understand your fury, Hendrik, but actually you know quite well that having no backup of your data is not too clever, even without feeding them to _some_ github project. And I know that this remark is no help now.)

Jörg

**Comment by leblancfg** [comment]
Hi everyone. My apologies for not having responded earlier. I aggressively removed Github notifications some months back , but I realize I should have kept this one active.

Special thank you to @joerg-s for e-mailing me to let me know.

The way the CLI is set up currently, indeed, we move the successfully cropped files. Given a few days, I can change the way this works. I will also gladly accept any PRs that modifies this behaviour.

-----

Now, for the drama part of this thread.

>**Who will compensate me for that loss?**
>Unfortunately for you, no-one, as [the license to this project clearly states](https://github.com/leblancfg/autocrop/blob/c471432df0da11d21c1bc9be7fab1e70f85e05a6/LICENSE#L19). Would you blame Ken Thompson if you mistakenly ran `rm -rf /`?

>**I can't express how furious I am!!! You f#&^%d up big time!**
>@HWiese1980, as much as I can sympathise with you right now, this is no place for this kind of language. I would appreciate if you could amend your previous comment to a more civil tone.

**Comment by HWiese1980** [comment]
> if you mistakenly ran rm -rf /

That's a totally different story. `rm`'s core purpose is to delete files. I can't blame a weapons manufacturer if I shoot myself in the foot, but I can totally blame a carpenter if I rip my skin on a jutting out nail! 

> this kind of language

How else am I supposed to express extreme anger, huh? With soft laundered language like, well, excuse me, but... you see... I'm terribly sorry, but you deleted a massive amount of files from my harddisk without even asking... you know, that kind of disturbes me a little bit. I'm so terribly sorry, I'll have to ask, but could you please, please, pretty please with a cherry on top, next time not? Thank you oh so very much!!! I appreciate that!

You *messed* up! Period! Now will you get that warning out, before more people wonder about the whereabouts of their files!

**Comment by leblancfg** [comment]
@HWiese1980, I don't see how your further venting here is any productive, and your behaviour is unacceptable.
