### ISSUE TITLE
add --no-reject option

### ISSUE THREAD

**Issue by echo6ix** [leblancfg/autocrop#124]
Add a parameter, `--no-reject`, to disable the output of rejected files to the filesystem.

**Comment by ASHWIN990** [comment]
@leblancfg do you think that it's good to have this flag, @echo6ix can you explain why you want this feature..

**Comment by leblancfg** [comment]
@echo6ix would this feature be as simple as running the tool with `autocrop -i input_dir -o output_dir -r reject_dir && rm -rf reject_dir`, such that rejected files are discarded?

**Comment by echo6ix** [comment]
@leblancfg you're correct. laziness was the initial reason i thought that'd be a good flag. it didnt take much to auto `rm -rf` the reject folder with an autocrop alias.
