### ISSUE TITLE
Switch to opencv-python-headless

### ISSUE THREAD

**Issue by ryboe** [leblancfg/autocrop#128]
Currently, autocrop uses `opencv-python`, which is meant for use in desktop environments. It depends on a bunch of desktop GUI dependencies, like Qt and X11. These are heavyweight dependencies that require lots of OS-level dependencies.

As an alternative, autocrop could use [`opencv-python-headless`](https://github.com/skvark/opencv-python#installation-and-usage), which is much smaller and doesn't have any of those GUI dependencies. I'm not certain, but I expect that most autocrop users are running it on servers. Those users would be best served by using `opencv-python-headless`.

Perhaps there should be two packages: `autocrop` (headless) and `autocrop-gui`?

**Comment by leblancfg** [comment]
Thanks for bringing this to my attention @ryboe, I had no idea it even existed! I see no reason to package autocrop with GUI dependencies; if people want these dependencies they are of course free to explicitly install it themselves.

I will certainly check into it more; one thing I notice from a cursory glance is the seeming difficulties of installing the headless version of Windows. But the appveyor tests should be able to shed some light on this.

**Comment by ryboe** [comment]
❤️ you @leblancfg 🎉 👏
