### ISSUE TITLE
PIL is not saving transparency, instead its bringing back background

### ISSUE THREAD

**Issue by emersonjr** [leblancfg/autocrop#131]
https://stackoverflow.com/questions/66702240/pil-is-not-saving-transparency-instead-its-bringing-back-background?noredirect=1#comment117910991_66702240

I'm using a python script to remove the background from a pic with a person and it's doing it pretty decently. Then i'm using autocrop to crop person's face on image, then i save that new pic. But when i check the new pic, its background is back again, like it hadn't been removed before. Why is it happening and how could i solve it? Any help is welcomed. Thanks beforehand!

Image with background removed below (yeh, not totally but its ok for what i need)
![image](https://user-images.githubusercontent.com/8794425/111729880-db1efd80-884e-11eb-84ef-4d5aec88f357.png)

And that's the image i get after cropping
![And that's the image i get after cropping](https://user-images.githubusercontent.com/8794425/111729910-ed00a080-884e-11eb-8b1d-e93c1f8763d3.png)

**Comment by leblancfg** [comment]
Thanks for reporting @emersonjr. This unfortunate effect has already been reported in issue #65, thanks for bringing it up again though.

To fix the problem in autocrop is doable, but requires substantial work in the way images are treated.

There's a suggested workaround with `imagemagick` in the linked issue above to remove the background. You can use the following steps to get the achieved result by automatically removing the background after passing through autocrop:

```sh
autocrop -i input_folder -o output_folder
find output_folder -name *.png -exec convert {} -fuzz 10% -transparent "rgba(15,38,88,1)" {} \;
``
