### ISSUE TITLE
Autocrop resize using cv2.resize() - suggest using PIL's Image.resize() method instead.

### ISSUE THREAD

**Issue by Tollanador** [leblancfg/autocrop#142]
After reading a recent paper: [On Buggy Resizing Libraries and Surprising Subtleties in FID](https://www.cs.cmu.edu/~clean-fid/), it appears that the resizing step in autocrop is potentially using a buggy resampling technique. PIL's resize was shown to correctly apply the various down-sampling methods (the _only_ one to in their testing) resulting in proper antialiasing.

This appears to be crucial if using the images as part of a training or testing dataset, particularly for StyleGan3. It may also lead to underlying problems elsewhere if the antialiasing is assumed to be correctly applied.

**Comment by leblancfg** [comment]
Thanks @Tollanador! That's very interesting indeed. In essence this would be a single-line change, right, affecting only this? https://github.com/leblancfg/autocrop/blob/51552da60e8ab54992a808399ca7960eaae9d064/autocrop/autocrop.py#L212-L215

Were you interested in submitting a PR? I'd just like you to benchmark the performance in this case, and make sure we're not inadvertently slowing things down. A simple `%timeit` in ipython between the two methods should suffice.
