### ISSUE TITLE
Please release precompiled wheels

### ISSUE THREAD

**Issue by ryboe** [leblancfg/autocrop#147]
v1.2.0 is only available as a tarball of the source.

```
https://files.pythonhosted.org/packages/d1/4f/10ff2c7f4b8870010b4fc3f6e644ff8cca82e167565c4021e6b8792287af/autocrop-1.2.0.tar.gz
```

Installing precompiled wheels is faster and less error-prone.

It might be worth it to start using [`poetry`](https://github.com/python-poetry/poetry) to manage your dependencies. Then you could create a tarball and wheel with one command.

```sh
poetry build
```

**Comment by leblancfg** [comment]
Thanks for the heads up @ryboe, the wheel for 1.2.0 are now uploaded, and will be released for upcoming releases.

Love the suggestion for `poetry` and have been using it for my other personal projects. I'll add that as a future enhancement. Cheers!

**Comment by ryboe** [comment]
Thank you so much @leblancfg !
