### ISSUE TITLE
art faces

### ISSUE THREAD

**Issue by nicolai256** [leblancfg/autocrop#172]
I want to train this so it recognises faces in artwork better, any idea how I can do that?
thanks

**Comment by leblancfg** [comment]
Sure! [Autocrop uses](https://github.com/leblancfg/autocrop/blob/a388919382ad0621a16dae7cf69533d832b16eaa/autocrop/autocrop.py#L177-L187) OpenCV's [Cascade Classifier](https://docs.opencv.org/3.4/db/d28/tutorial_cascade_classifier.html). Here's an [article on how to train your own](https://pythonprogramming.net/haar-cascade-object-detection-python-opencv-tutorial/).
