### ISSUE TITLE
Blue-ish shade on cropped pictures

### ISSUE THREAD

**Issue by Nathanielna** [leblancfg/autocrop#175]
![image](https://user-images.githubusercontent.com/47273938/184778128-a44ebd03-c191-4d65-bef0-1899fc54721f.png)
windows 10  ，From the command line ，autocrop 1.3.0
I see that some people have fed back this issue in 2020，What shall I do?

**Comment by Nathanielna** [comment]
![d557c6617aa5628d64a3c76bd78c01de](https://user-images.githubusercontent.com/47273938/184778961-fc27ca09-d628-443e-903f-ca7e7badfb8d.jpeg)
This is the original picture

**Comment by Nathanielna** [comment]
Yes, I use the wrong method. Please close the issue

**Comment by clreinki** [comment]
I'm having the same issue, how did you fix?
