### ISSUE TITLE
Sometimes no faces to crop are found

### ISSUE THREAD

**Issue by BeginnerCow** [leblancfg/autocrop#185]
Hello, I tested this package and I really like it but sometimes it does not find a face to crop (when the whole person is in the image). Is this intended (e.g. I'm using it not with intended images?) or some kind of bug?

E.g. I tried to use it on this free stock photo: https://unsplash.com/photos/NDCy2-9JhUs

The output tells me, that there is no face found in this image (it works on other images though).

Thank you!

**Comment by graphixillusion** [comment]
Yep i confirm, many faces are not detected

**Comment by liuchangzong** [comment]
I have the same question. Is there anything we can do to promote it??

**Comment by leblancfg** [comment]
Closing as "wontfix", but PRs absolutely welcome if folks want to take on using another algorithm for face detection.
