### ISSUE TITLE
PackageNotFoundError opencv >=2.4.9

### ISSUE THREAD

**Issue by renopp** [leblancfg/autocrop#2]
<img width="595" alt="screen shot 2017-09-17 at 11 55 12 am" src="https://user-images.githubusercontent.com/11856209/30518138-3469a836-9b9f-11e7-9ff7-ca2d1ab73aa4.png">
try to install with conda, but can't find opencv 2.4.9

```
PackageNotFoundError: Packages missing in current channels:
            
  - opencv >=2.4.9

We have searched for the packages in the following channels:
            
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```

**Comment by leblancfg** [comment]
Will need to create an `environment.yml` file so that we can specify what conda channel to look in (conda-forge is where opencv lives)'

In the meantime, you can use: `conda install -c conda-forge opencv` to install that dependency.

**Comment by leblancfg** [comment]
Updated `README.md` to highlight this detail. Will not be using `environment.yml` for now, as this problem would better be solved by creating a PyPI package and conda-forge recipe.

Hopefully the wording for the installation steps is now clear.

**Comment by renopp** [comment]
thanks fot the update
