### ISSUE TITLE
Creating folder

### ISSUE THREAD

**Issue by stml** [leblancfg/autocrop#25]
Thanks for this, it's great. I thought I'd note that if I don't manually create `bkup` and `crop` directories in the photos directory before executing, these are not created. Instead, a single image called `bkup` and another one called `crop` are generated, and then repeatedly overwritten, removing all the other images. I'm not sure if this is intended, but it's certainly unexpected, and should perhaps be either fixed or explained in the Readme.

**Comment by leblancfg** [comment]
Ouch, you're quite right. That behaviour made sense when the script was called from `python autocrop.py` with a standard folder layout, but quite useless when called directly.

Changing this will break previous scripts using `autocrop`. I'm OK with this, as it seems like a glaring hole in the interface, and probably prevents new users from successfully / easily using it.

Proposed behaviour:
- Add `-o`, `--output` flag to specify directory where cropped images are to be dumped.
    * Error out if output folder set to current directory, i.e. `-o .`
    * If directory doesn't exist yet, create it.
    * If no face can be found in an image in batch, it is still copied over to `-o` folder.
    * If no output folder is added, ask for confirmation (`[Y]/n`), and destructively crop images in-place.
        + Confirmation can be skipped with `--no-confirm` flag.
- Use `-i`, `--input` flags as synonyms for `-p` or `--path`: symmetrical in meaning to "output".
    * To become standard nomenclature in documentation.
- `--input` or `--path` flag to become optional.
    * Standard behaviour without input folder will be to non-recursively process all images in immediate folder, i.e. `-p .` as currently implemented.

Backing up images then becomes redundant.

I'll leave this open for comments for a week, then fix it. Let me know if there's something I'm missing.

**Comment by stml** [comment]
That seems good. I probably should have mentioned the additional - quite major - issue I'm experiencing (Python 2.7.12, Ubuntu 16.04), which is that none of the options work for me. If I simply run the `autocrop` command, it processes the images in `photos` according to the defaults, but if I add any options, it just outputs the help text, e.g.:

```
(cv) root:~/Documents/AWS$ autocrop -p chaplin/ -w 250 -h 250
usage: autocrop [-h] [-p PATH] [-w WIDTH] [-H HEIGHT] [-v]

Automatically crops faces from batches of pictures

optional arguments:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  Folder where images to crop are located.
                        Default=photos/
  -w WIDTH, --width WIDTH
                        Width of cropped files in px. Default=500
  -H HEIGHT, --height HEIGHT
                        Height of cropped files in px. Default=500
  -v, --version         show program's version number and exit
(cv) root:~/Documents/AWS$
```

**Comment by mbedded** [comment]
Thanks for the workaround to create the folders before i use that script. I was struggling withe the same issue that multiple pictures were renamed to `crop` and `bkp` so my files got deleted and the script overwrote the files when calling the script via shell.
The parameters are working under windows CMD when i call: `python autocrop -p MY_PATH -w 250 -H 250`

Btw: Good feature that you output (and don't move) the files where the face cannot be found.

**Comment by leblancfg** [comment]
Hopefully this works for your needs. The function is now fully tested on all three OSes, but don’t be afraid to open another issue if it persists.

On a personal note, I’d love to hear how cropping your chaplin folder turned out @stml ! 🙂 leblancfg@gmail.com
