### ISSUE TITLE
New parameter: "--file" for single-file processing

### ISSUE THREAD

**Issue by mbedded** [leblancfg/autocrop#27]
Hello François,

i discovered your repository some days ago. It is a pretty nice project.
I would like to have an additional parameter like `--file` to single-process only one file instead of a folder.

Maybe there could be a 2nd argument to define the path of the crop-result.

I will see if i can do such changes. I have done some smaller things with python.
As first i have to install your package via pip and see how it works.

**Comment by leblancfg** [comment]
That's an excellent idea. Marked for future enhancement.

Thanks for letting me know!

**Comment by leblancfg** [comment]
Closing this. Further discussion in #30.
