### ISSUE TITLE
New parameter: "--file" for single-file processing

### ISSUE THREAD

**Issue by mbedded** [leblancfg/autocrop#30]
Hi François,

version 0.2.0 works good. I like the specification of input and output folder. If i am the only one asking for #27 i guess you can ignore that request. I can work with "input" and "output" aswell. So i don't need a special --file-input when my input folder just contains one file.

But i have a minor issue caused by the new behavior (excerpt from Readme):

```
Readme.md (0.1.5)
  Images where a face can't be detected will be left in `pics`.
  (Originals are moved to 'backup', 'crop' contains cropped images.
  Original folder contained uncropped ones.

Readme.md (0.2.0)
  1. Copy all images found in the top level of `pics` to `crop`,
  [...]
  Images where a face can't be detected will be left in `crop`.
```

I face the problem, that i can't identify which images are not cropped, if the files are copied into `crop`-folder. Let's say i do a batch-crop of 100 images. Before i was able to validate a cropping of all images by count the number of files or do a filename-compare.
If `crop` contains 90 files, the 10 original ones stay where they are.

Now:
I want to crop 100 images. All 100 files are copied to `crop`. But i have to check manually the size of the images (by given width and height) or `open explorer > show as thumbnail` and take a look if all images are cropped. As alternative i could read the console output and use something like grep.

In my application, i want to auto-crop an image of yourself to use this as a profile-picture. The application checks if the file is existing in folder `crop`. If yes: it's alright, if no i can do some error handling (e.g. let the user upload another picture).

The application i write is a C#-one. So the only way to detect a (possible) not-cropping is by compare original file and the output in `crop` (maybe hash or image-resolution). As alternative i could check the text-output of autocrop if there is something like "No faces can be detected in FILENAME". But as always with texts: What happens if the text changes somewhere? Human-read text may change at any time. I may not use this solution.

What do you think about that behavior? Should it be like the old one? Maybe a flag like 'crop behavior' helps to distinguish between 'copy all and then try crop', 'copy cropped only'. In the end of the day you are the maintainer and you can decide which features may be needed or which are useful :)
This are just my personal thoughts about the changes.

**Comment by leblancfg** [comment]
Hi @mbedded,

The plan for now is to add the capability to process single files, as in #27. You'd be able to know if autocrop succeeded, failed or errored by the exit code.

No need for a `--file` flag either, since we can invoke that command directly by `autocrop filename.jpg`.

We need to think of all the ways this new functionality needs to work, though, when paired with other arguments. I don't know the Windows way of expressing a few of these, but here are my concerns for the API before I start the work:
1. [ ] `autocrop filename.jpg` should crop the image in place. Not sure if it should prompt for confirmation, though. I don't think Imagemagick does, for example.
2. [ ] Calling from piped arguments in the shell needs to work well, e.g. `find . -name 'expression' | xargs autocrop -o 'foldername'`. What happens when autocrop can't find an image in one of those files? Need to research proper use of exit statuses both for POSIX and Windows.
3. `autocrop filename.jpg -o folder` makes sense to me, place the cropped image in `folder`.
    * [X] If that directory doesn't exist, create it.
    * [ ] If `folder/filename.jpg` already exists, should it fail, prompt for overwrite, or simply ovewrite?
4. [X] `autocrop filename.jpg -i folder` doesn't make sense to me. Error out.
5. [X] `autocrop -w` and `-H`: same behaviour as currently implemented.

If that's OK, I'll close #27 and use this issue for discussion.

**Comment by mbedded** [comment]
Hi @leblancfg,

sure you can close #27 as i suggested at top. I didn't know exactly what tasks were planned as next implementations. I was just confused because of the different handling, so i started this issue for discussing 😄 

> You'd be able to know if autocrop succeeded, failed or errored by the exit code.

What do you mean with this sentence exactly? Is this a new feature or how am i able to get the exit code. When i call (via console) `autocrop -i Input -o Output` all images from `Input` are in `Output`. It does not matter if they could be cropped or not. Correct me when i am wrong, but now you call `autocrop` with your parameters and the console output is only "no face detected in FILE" and then the application returns no error (in the current state).

I tried the following:
`autocrop -i Input -o Output
Processing images in folder: C:\test\Input
[ INFO:0] Initialize OpenCL runtime...
No faces can be detected in Image1.jpg.
No faces can be detected in Image2.jpg.
 47 files have been cropped
`
When i call `%errorlevel%` (Windows CMD) it returns 0. So currently this is not possible (i understand your sentence in the way, that this error-code will be changed in the future).

As idea for cropping in place or lets say "destructive cropping". Personally i like it more when the application does not overwrite files without an explicit argument. From my point of view there is nothing worse than a tool you try and destroy your original file accidentally (but that's only my opinion, other people see it the other way round).

Referring to 1)
`autocrop filename.jpg` should create a new file so you have: filename.jpg and filename_new.jpg (i think a safe way is better). As an alternative: A user must specify `-f (force)` to force overwrite or he has always to give input-name and output-name like `autocrop filename.jpg outputFilename.jpg` (but this is close to `-o`).

Referring to 3)
I guess it should be the same as in 1. If there is a file already existing -> output error.
Alternatively `-f` as additional parameter to force overwrite.

The other points: I see them in the same way as you do. Unfortunately i am not that experienced with python and arguments, so i am unsure how much work a new argument (like -f) causes.

**Comment by leblancfg** [comment]
Excellent! Thanks for the review, I'll get started on the spec.

For numbers 1 and 2, that absolutely makes sense to me, and I'll go with that.

As for point number 2, yes, I think we're saying the same thing. By cropping single files (and not a whole folder full of files), the cropping process now either succeeds or fails, and we can emit that as an exit status on stderr. Calling autocrop from other languages or in shell scripts would be easier to control this way.

**Comment by leblancfg** [comment]
An update on this: I've put some work in [branch issue-30](https://github.com/leblancfg/autocrop/tree/issue30), and probably won't have time to take it on for a few couple of months.

It's there for the taking if someone wants to take that baton.
