### ISSUE TITLE
improve options parsing

### ISSUE THREAD

**Issue by mechanomi** [leblancfg/autocrop#42]
The current options parsing code is a little difficult to work with and doesn't produce the best output in my opinion

I am open to suggestions, but at the moment, I expect that moving to the [click](https://pypi.org/project/click/) library is a good choice for this project

see it in action on one of my projects:

https://github.com/mechanomi/mimicbot/blob/master/src/mimicbot/cli.py

**Comment by leblancfg** [comment]
As I'm slowly shifting the focus of the tool to the Python API, I think this will need to get resolved with the #wontfix tag.

Ultimately, I think there is a lot of good to "encapsulate" the current CLI API that works with folders into a `autocrop -d` flag, and make the default CLI behaviour focus on single images, à la [facedetect](https://www.thregr.org/~wavexx/software/facedetect/). This would align with standard Unix practices.
