### ISSUE TITLE
Refactor to CroppableImage class

### ISSUE THREAD

**Issue by leblancfg** [leblancfg/autocrop#47]
A lot of enhancements have been added to what started off as a single-file script, and the number of arguments passed to the main functions is starting to get out of hand.

Suggested course of action:

1. Consolidating the four `padding` variables to a single named tuple.
2. Moving the "image-cropping" functions as functions of a `CroppableImage` class
3. Refactor tests

Prerequisite to #18 and #27.

Along those lines, I am starting to think that autocrop's default should be #27's suggestion of per-file action, and that the current API could be nested into a `autocrop folder` flag instead. Will open that discussion once this and the other two cited issues are merged and closed.

**Comment by bastians** [comment]
Maybe you could also replace the padding variables by two variables for x and y axis, Like Pixnub ist doing it: https://youtu.be/4r917cyzuoc

Btw: How dies the padding work currently? 😇 Do you have a visual example?
