### ISSUE TITLE
Only have cropped images in crop folder

### ISSUE THREAD

**Issue by ak9250** [leblancfg/autocrop#48]
As it is right now it is hard to locate the cropped images, possibly only add the cropped images to the crop folder? I have a folder of 100 or a 1000 images I wont be able to locate the crop ones fast.

**Comment by mechanomi** [comment]
this should be fixed with https://github.com/leblancfg/autocrop/pull/40

**Comment by ak9250** [comment]
@mechanomi ok any timeline when this will be merged?

**Comment by mechanomi** [comment]
@ak9250 not sure. probably "soon"

**Comment by ak9250** [comment]
@mechanomi ok, anyway to use it before it is merged?

**Comment by mechanomi** [comment]
@ak9250 you can try your look building from source from my branch. check out the CONTRIBUTING file for instructions

**Comment by leblancfg** [comment]
@ak9250 package 0.3.1 is now updated on pypi, and should be usable on all platforms. Thanks for the heads up!
