### ISSUE TITLE
false positives in detecting faces?

### ISSUE THREAD

**Issue by ak9250** [leblancfg/autocrop#51]
Hi, thanks for adding the reject folder it works well but sometimes there are some false positive in the cropped folder. So far I tried it on about 300 images and it put 87 in cropped folder. Then I checked those 87 by combining 80 of them into a 9x9 collage and saw that there were images in cropped folder that did not have faces.

**Comment by leblancfg** [comment]
@ak9250, any luck playing around with this at all?
/remind me in a week

**Comment by leblancfg** [comment]
Closing this for now @ak9250 . Feel free to ping me back at anytime and we can re-open it. Like I said, I'm willing to look into using a CNN solution instead of OpenCV's Haar Cascades.
