### ISSUE TITLE
fold requirements-test.txt into requirements.txt

### ISSUE THREAD

**Issue by mechanomi** [leblancfg/autocrop#52]
as far as I can tell, there is no need for ``requirements.txt`` and ``requirements-test.txt``

``setup.py`` has the requirements used by pip when installing from PyPI. the ``requirements*.txt`` files are only used by a developer

which means, I *think*, that they can be folded into a single ``requirements.txt`` file, and the contributing docs can change the line referencing ``requirements-test.txt`` to reference ``requirements.txt``

**Comment by leblancfg** [comment]
Good point, there is certainly duplication. Haven't done thorough research to see what's standard practice, but I also see the converse being used in other projects:

~~~python
with open('requirements.txt') as f:
    REQUIRED = f.read().splitlines()
~~~

Thoughts?

**Comment by mechanomi** [comment]
you could take it one step further and have a single `requirements.txt` file but stop reading in the lines after a comment string indicating that everything following that comment is a testing/development requirement

I'm not sure. I'm not particularly experienced with PyPI best practices! all I know is that I haven't seen the `-test.txt` thing before

**Comment by leblancfg** [comment]
Well to be fair, nor am I! :smile:

I do see `requirements-dev.txt` files along with `requirements.txt` in many repos though:
https://github.com/search?q=%22requirements-dev.txt%22&type=Commits

My bad for naming it `-test` and not `-dev`, but that's fixable.

### Suggested outcome
1. Rename `requirements-test.txt` to `requirements-dev.txt`
2. Keep `requirements.txt` as-is
3. Change [lines 22-25 in `setup.py`](https://github.com/leblancfg/autocrop/blob/374a29751432245fe153efb0de80192b8a15842e/setup.py#L22) to the snippet in the comment above
4. Update `CONTRIBUTING.md` to reflect the change in filename

How does that sound?

**Comment by mechanomi** [comment]
yeah sounds good!

**Comment by leblancfg** [comment]
Closing this in favour of #67, reusing parts of suggested outcome.

**Comment by mechanomi** [comment]
#68 doesn't appear to exist any longer?

**Comment by leblancfg** [comment]
Oops, typo. #67 :)

**Comment by mechanomi** [comment]
cool thanks!
