### ISSUE TITLE
Crop without resizing

### ISSUE THREAD

**Issue by cedoard** [leblancfg/autocrop#57]
Hi,

is it possible to just crop faces without resizing it? 

Unfortunately, I have low quality images and resizing after cropping, made them really blurry.

Thanks!

**Comment by ASHWIN990** [comment]
Hey @leblancfg wanted to work on this, with a flag **--no-resize**

*Can you assign this to me*

**Comment by ASHWIN990** [comment]
Kinda working on this feature, what i was thinking that, what will be the size of the image if we didn't resize it, like @leblancfg has already setup a default size of 500x500 px, so what are your views.

@leblancfg @cedoard @ASHWIN990

**Comment by leblancfg** [comment]
If we don't resize, that means we just return whatever pixels are in the cropped pic.

**Comment by ASHWIN990** [comment]
Yes exactly, there is a step in the cropper class which resize the image if no param given then 500x500 so if the flag --no-resize is passed the step will simply skip, i've done all the testing manually, but struggling the unit test code, although learning it....

**Comment by tiwari93** [comment]
Remove line 211 to 213 in autocrop.py file. It will return crop image without resizing.
