### ISSUE TITLE
Transparent PNGs get random noise on backgrounds.

### ISSUE THREAD

**Issue by esbenvb** [leblancfg/autocrop#65]
```
$ pip install autocrop
$ autocrop --version
autocrop version 0.3.1
$ autocrop --input . --output cropped --reject rejected --facePercent 50 --width 200 --height 200
```
Input

![30-mikelagu](https://user-images.githubusercontent.com/426051/57844803-08bd3a80-77d1-11e9-8c49-aae5a21ab8d8.png)
![allefandrade](https://user-images.githubusercontent.com/426051/57844804-0955d100-77d1-11e9-8700-594b21e3f1c6.png)
![andresousa](https://user-images.githubusercontent.com/426051/57844805-0955d100-77d1-11e9-89ad-d6815319e6d8.png)
![andrepedrosa](https://user-images.githubusercontent.com/426051/57844806-0955d100-77d1-11e9-8575-452df767cbd4.png)

Result

![andresousa](https://user-images.githubusercontent.com/426051/57844880-29859000-77d1-11e9-8d7d-c44ed6d1fffb.png)
![30-mikelagu](https://user-images.githubusercontent.com/426051/57844881-2a1e2680-77d1-11e9-919f-f95fa16b0467.png)
![allefandrade](https://user-images.githubusercontent.com/426051/57844883-2a1e2680-77d1-11e9-9c06-225a995b2745.png)
![andrepedrosa](https://user-images.githubusercontent.com/426051/57844884-2a1e2680-77d1-11e9-9544-6e37ec558a15.png)

**Comment by leblancfg** [comment]
Saving relevant StackOverflow to come back to later:
https://stackoverflow.com/questions/53380318/problem-about-background-transparent-png-format-opencv-with-python

**Comment by esbenvb** [comment]
Temporary workaround using imagemagick:

```
$ for FILE in *.png; do convert "$FILE" -background "#ffffff"  -flatten "$FILE";  done
```
