### ISSUE TITLE
Process every frame of an animated gif

### ISSUE THREAD

**Issue by norosa** [leblancfg/autocrop#69]
I think it might be cool to process every frame of an animated gif, and output a bunch of sequentially numbered files for each face detected

creating this issue for myself, as this is something I might want to work on

**Comment by leblancfg** [comment]
Great idea! Seems like everything required is already in OpenCV, too:

https://github.com/asharma327/Read_Gif_OpenCV_Python/blob/2e97bfa414566c5d7a4b9b7569f96b4e5aef2fb5/gif_to_pic.py#L10

**Comment by leblancfg** [comment]
See #136
