### ISSUE TITLE
New parameter "--original" to save the original image file to a different path

### ISSUE THREAD

**Issue by NeighborGeek** [leblancfg/autocrop#78]
Add an option to retain the original image file instead of deleting it.  The parameter could accept a path where the original image is moved to after it has been processed.

**Comment by leblancfg** [comment]
Hi @NeighborGeek, If I'm understanding it right, that functionality is something that can be easily achieved straight from the command line, right? 

    cp folder other_folder && autocrop folder

If that's it, I'd probably not want to add that. But let me know if I'm not getting it what you meant!

**Comment by leblancfg** [comment]
Closing this for now, but please re-open if I didn't get this correctly.
