### ISSUE TITLE
pip3 install autocrop

### ISSUE THREAD

**Issue by birdsoftware** [leblancfg/autocrop#82]
I get the error: pip: command not found

It's because the python3 path (\bin) doesn't have "pip" anymore, it has "pip3". Open your terminal and type "pip3 -v" and I'm sure you'll see it's there. Ever since Python 3.5 pip has been included with Python but they renamed it slightly. Hope that helps. – S Walsh Feb 28 '19 at 0:59

**Comment by leblancfg** [comment]
Hi S,

Thanks for raising the point! What you're saying is true, but only for systems where both Python versions are installed (Ubuntu/Debian/macOS). The user may also set it up differently, e.g. if they're in a virtualenv, using the Anaconda distribution, if they're on another Linux distribution, on Windows, etc.

For the moment at least, autocrop can be run on both 2.7 and 3.5+, so we're giving users the option.

Ultimately it's up the user to know how to install packages with pip on their particular setup. For now, I'll stick with how the [Python Package Authority recommends packages be installed](https://pypi.org/project/autocrop/), and close this issue.

Cheers!
-fl
