### ISSUE TITLE
badges in README are broken

### ISSUE THREAD

**Issue by mechanomi** [leblancfg/autocrop#83]
a couple of the badges in the README are broken

**Comment by mechanomi** [comment]
I refreshed and they started working lol nvm

**Comment by leblancfg** [comment]
lol thanks for the herads up tho!

**Comment by mechanomi** [comment]
reopening actually. the vulnerabilities button is pretty much always broken. I would suggest to remove it. the integration will continue to work, but the REAME won't look broken

**Comment by leblancfg** [comment]
Sounds good to me, thanks!
