### ISSUE TITLE
what is the 🆔about in the project description?

### ISSUE THREAD

**Issue by mechanomi** [leblancfg/autocrop#84]

**Comment by leblancfg** [comment]
😆 I initially wrote autocrop to automate ID picture cropping. Absolutely open to using another emoji, open to suggestions!

**Comment by mechanomi** [comment]
hehe I would just suggest to drop it :)

**Comment by leblancfg** [comment]
That makes sense, but I do like having an emoji there 🤣 I think I might just swap for a face instead. Thanks for the period suggestion though, definitely adding that.
