### ISSUE TITLE
Fix the padding mechanism

### ISSUE THREAD

**Issue by leblancfg** [leblancfg/autocrop#89]
The padding arguments are broken in many examples, and the mechanism for its use is unclear.

Steps to reproduce:
~~~python
from autocrop import Cropper
from PIL import Image
loc = 'tests/data/macbeth.jpg'

c = Cropper()
# Compare this
Image.fromarray(c.crop(loc))

# To this
c.padding=100
Image.fromarray(c.crop(loc))

# Or this
c.padding = {
        "pad_top": 0,
        "pad_right": 0,
        "pad_bottom": 1000,
        "pad_left": 0,
    }
Image.fromarray(c.crop(loc))
~~~
![autocrop_padding](https://user-images.githubusercontent.com/15659410/76969278-8e81a900-6900-11ea-940c-ca40f2286d48.png)

This issue will be solved with:
- fixing the actual mechanism
- updating the documentation to clarify how it differs from the `(width, height)` and `face_percent` parameters.

@mechanomi, if you've got some spare cycles I'd love to understand what you had in mind when implementing it. I don't think I touched your code when refactoring in #88, but any context would help. Thanks!

**Comment by mechanomi** [comment]
I don't think this was my change

the only relevant pull request I could find was this: https://github.com/leblancfg/autocrop/pull/35/files

I don't' use this feature

I think maybe blame shows me editing those lines bcus I maybe refactored the CLI arg parsing stuff? idk

**Comment by leblancfg** [comment]
Makes sense. Thanks for checking it out though!
