### ISSUE TITLE
opencv2 vs. 3 issues

### ISSUE THREAD

**Issue by peterpme** [leblancfg/autocrop#9]
Hello,

Awesome library, thank you!

requirements.txt asks for opencv >= 2.4.9.
3+ is whats available on pip and installing ~2 doesn't seem to be possible.

Do you know how to install 2.4.9?

Otherwise I think another option is to update cv2 to support cv3 api

Thanks!

**Comment by leblancfg** [comment]
You're absolutely right. The way to go is to support cv3. New set of commits on the way in a few days in branch `issue-008` that will be fixing that issue.

Thanks for letting me know btw, that's really useful!

**Comment by leblancfg** [comment]
Should be fixed at this point.
