### ISSUE TITLE
Cannot import Cropper and autocrop has no cropper attribute.

### ISSUE THREAD

**Issue by hackerncoder** [leblancfg/autocrop#96]
Hello!

Yes, I am somewhat new to python.

My problem is that no matter how I try to import, call or otherwise get the Cropper function, python will just throw an error:

`cropped_array = autocrop.Cropper('portrait.png')
AttributeError: module 'autocrop' has no attribute 'Cropper'`

`ImportError: cannot import name 'Cropper' from 'autocrop'`.

I know this might be a general python error, but I just cant figure out what is causing the problem.

**Comment by leblancfg** [comment]
So sorry @hackerncoder, I haven't updated the PyPI package yet! I'm still fixing a critical bug, and once that's fixed, it will be there.
